plugins {
    id 'com.android.application'
}

def placesApiKey = project.findProperty('PLACES_API_KEY') ?: System.getenv('PLACES_API_KEY') ?: 'NO_KEY'

android {
    namespace 'com.mrone.fieldapp'
    compileSdk 35

    defaultConfig {
        applicationId 'com.mrone.fieldapp'
        minSdk 28
        targetSdk 34
        versionCode 143
        versionName '1.4.3'
        manifestPlaceholders = [PLACES_API_KEY: placesApiKey]
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}


dependencies {
    implementation 'com.google.android.libraries.places:places:5.3.0'
    implementation 'com.google.android.material:material:1.12.0'
}
