plugins {
    id 'com.android.application'
}

android {
    namespace 'com.mrfieldbook.app'
    compileSdk 35

    defaultConfig {
        applicationId 'com.mrfieldbook.app'
        minSdk 28
        targetSdk 34
        versionCode 9
        versionName '9.0.0'
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
